select md5(concat(c.customer_id,
       c.email,
       c.store_id,
       c.last_name,
       c.address_id,
       c.first_name,
       c.create_date,
       c.modified_at)::TEXT) as SK_customer,
       c.customer_id,
       c.email,
       c.store_id,
       c.last_name,
       c.address_id,
       c.first_name,
       c.create_date,
       c.modified_at
from {{ ref('stg_customer') }} c
